version: '3'

volumes:
  db: {}
  images: {}

services:
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - private_wiki_db:/var/lib/mysql
    env_file:
      - ./compose/database.env

  wiki:
    image: lego3410/wiki:latest
    build:
      context: ./compose
      dockerfile: ../Dockerfile
      args:
        MEDIAWIKI_VERSION: 1.34.2
    restart: unless-stopped
    networks:
      - default
      - proxy
    volumes:
      - images:/var/www/html/images
    env_file:
      - ./compose/database.env
      - ./compose/wiki.env
    labels:
      - "traefik.docker.network=proxy_default"
      - "traefik.http.routers.public-wiki.rule=PathPrefix(`/wiki/`, `/w/`) || Path(`/`, `/wiki`)"
      - "traefik.http.routers.public-wiki.tls=true"
      - "traefik.http.routers.public-wiki.tls.certresolver=letsencrypt"
      - "traefik.http.routers.public-wiki.middlewares=replace_w"
      - "traefik.http.middlewares.replace_w.replacepathregex.regex=^/w/(.*)"
      - "traefik.http.middlewares.replace_w.replacepathregex.replacement=/$$1"

  parsoid:
    image: thenets/parsoid:0.11
    restart: unless-stopped
    environment:
      - PARSOID_DOMAIN_wiki=http://wiki/api.php

  # elasticsearch:
  #   image: elasticsearch:6.5.4
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node

networks:
  proxy:
    external:
      name: proxy_default
