version: '3'

volumes:
  private_wiki_db: {}
  private_wiki_images: {}
  private_wiki_assets: {}

services:
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - private_wiki_db:/var/lib/mysql
    env_file:
      - ./compose/database.env

  wiki:
    image: mediawiki:stable
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - private_wiki_images:/var/www/html/images
      - private_wiki_assets:/var/www/html/resources/assets
      - ./compose/extensions:/var/www/html/extensions
      - ./compose/skins:/var/www/html/skins
      - ./compose/LocalSettings.php:/var/www/html/LocalSettings.php
    env_file:
      - ./compose/database.env

  parsoid:
    image: thenets/parsoid:0.10
    restart: unless-stopped
    environment:
      - PARSOID_DOMAIN_wiki=http://wiki/api.php
