version: '3'

volumes:
  nginx_cert: {}
  private_wiki_db: {}
  private_wiki_images: {}
  private_wiki_assets: {}

services:
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - private_wiki_db:/var/lib/mysql
    env_file:
      - ./compose/db/database.env

  wiki:
    image: mediawiki:stable
    restart: unless-stopped
    # ports:
    #   - 80:80
    #   - 443:443
    volumes:
      - private_wiki_images:/var/www/html/images
      - private_wiki_assets:/var/www/html/resources/assets
      - ./compose/wiki/extensions:/var/www/html/extensions
      - ./compose/wiki/skins:/var/www/html/skins
      - ./compose/wiki/LocalSettings.php:/var/www/html/LocalSettings.php
    env_file:
      - ./compose/db/database.env

  parsoid:
    image: thenets/parsoid:0.10
    restart: unless-stopped
    environment:
      - PARSOID_DOMAIN_wiki=http://wiki/api.php

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./compose/nginx/cert/letsencrypt:/etc/letsencrypt
      - ./compose/nginx/conf:/etc/nginx/conf.d
      - ./compose/certbot/conf:/etc/letsencrypt
      - ./compose/certbot/www:/var/www/certbot
    env_file:
      - ./compose/nginx/server.env
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./compose/certbot/conf:/etc/letsencrypt
      - ./compose/certbot/www:/var/www/certbot
    env_file:
      - ./compose/nginx/server.env
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
