providers:
  docker: {}
  file:
    directory: /etc/traefik/config/

entrypoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    # http:
    #   tls:
    #     domains:
    #       - main: 2js.dev
    #     certResolver: letsencrypt

api:
  dashboard: true

log:
  level: DEBUG

certificatesResolvers:
  letsencrypt:
    acme:
      email: lego3410@gmail.com
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
