providers:
  docker: {}
  file:
    directory: /etc/traefik/config/

entrypoints:
  localhost:
    address: "127.0.0.1:80"

  web:
    address: ":80"
    https:
      redirections:
        entrypoint:
          to: websecure

  websecure:
    address: ":443"

api:
  dashboard: true

log:
  level: WARN
