providers:
  docker: {}
  file:
    directory: /etc/traefik/config/

entrypoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

api:
  dashboard: true

log:
  level: WARN

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${WG_EMERGENCYCONTACT}
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
